name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: get IWYU
        run: sudo apt-get install iwyu -y
      - name: Build code
        run: |
          cmake -S ${{ github.workspace }} -B build && cmake --build build
