name: GitHub Actions ubuntu latest
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: get IWYU
        run: sudo apt-get install iwyu -y
      - name: iwyu version
        run: include-what-you-use --version
      - name: Build code
        run: |
          cmake -S ${{ github.workspace }} -B build && cmake --build build
